### ISSUE TITLE
BackEnd error handeling

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#1]
Instantiating BackEnd should not open a connection, that functionality should be a callable method in order to handle errors. Method should probably ```throw``` errors in order to be handled by FrontEnd.

**Comment by legomaniack** [comment]
Actually, should be either/or. It should either ```throw``` an error, or it should return an error code. Both would be stupid and redundant.

**Comment by lekro** [comment]
Sounds good. Will do when I have time.

**Comment by legomaniack** [comment]
Fixed
