### ISSUE TITLE
Server does not disconnect clients on close

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#14]
Should boot them to login screen. FrontEnd.returnToLogin() may need to be made public for backend to handle.

**Comment by legomaniack** [comment]
Also will probably have issues on logout trying to send close message to server that doesn't exist. Close clients before server?

**Comment by lekro** [comment]
I think the server is sending QUIT messages to the clients, but I might have mistakenly put System.exit(0) before that. But maybe not.

**Comment by lekro** [comment]
It's not that the server isn't sending the QUIT messages, it's that the clients aren't handling them.... will fix.
