### ISSUE TITLE
Please fix the syntax error thing in RoomFile

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#2]
It's driving me insane, but I don't know what you want to do with it.

**Comment by rpbeltran** [comment]
What error? I don't see any syntax errors in eclipse, and the methods have all been tested and work.

**Comment by legomaniack** [comment]
Eclipse keeps complaining ```The method readAllLines(Path, Charset) in the type Files is not applicable for the arguments (Path)```

**Comment by rpbeltran** [comment]
Weird, I am not getting that.

**Comment by rpbeltran** [comment]
Try this:
Files.readAllLines(Paths.get(filepath), Paths.get(path), Charset.defaultCharset());

If it works for you, you can commit it or else I will.

**Comment by rpbeltran** [comment]
I think the issue is for Java 7 only, I bet you are using Java 7. Good catch.

**Comment by legomaniack** [comment]
That's too many arguments. The second is extraneous. Also, Charset needs to be imported. Otherwise, commit it.

**Comment by rpbeltran** [comment]
Wait, what argument is extraneous?

**Comment by legomaniack** [comment]
Whoa, nevermind. It copied *very* strangely.

**Comment by rpbeltran** [comment]
Ok. Cool. Do you want to commit it or do you want me to?

**Comment by legomaniack** [comment]
Go ahead and commit it. I'll close the issue.

**Comment by rpbeltran** [comment]
Done.

**Comment by lekro** [comment]
Wao all dem comments
