### ISSUE TITLE
Message handleing

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#4]
The server should probably send messages back to the client in the form of "messages since x time" rather than "here's all the messages". Would stop excessive data, and allow for non synchronized client things, line local console message type stuff. Just a thought.

**Comment by rpbeltran** [comment]
Currently it isn't sending anything is it?

**Comment by lekro** [comment]
The server isn't currently sending anything to the client. It's just receiving messages from the client and printing them out, no matter what they are.

**Comment by rpbeltran** [comment]
Ok, we can probably work on that tomorrow.
