### ISSUE TITLE
JComboBox ActionListener fires twice

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#5]

**Comment by rpbeltran** [comment]
Even better

**Comment by lekro** [comment]
More fire, more good.

**Comment by lekro** [comment]
Hm, I have seen it fire even three times.

**Comment by rpbeltran** [comment]
I don't have time to look at the code at the moment, but when you say ActionListener, shouldn't it be an item listener and something like this:

public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED) {
                      \\Code               
                 }
}

Maybe that is what you have, but you said ActionListener so I don't know.

**Comment by rpbeltran** [comment]
Here is an example: http://stackoverflow.com/questions/330590/why-is-itemstatechanged-on-jcombobox-is-called-twice-when-changed

**Comment by legomaniack** [comment]
I was not calling it for the event changed, I was trying to have a listener for pressing enter in the text field. Probably need one for onChange too, or maybe they're the same thing. Knowing Java, that probably means we need 3 different classes of Listeners. :/

**Comment by legomaniack** [comment]
Alright, this is actually causing a serious issue now that events actually *do* something. The server is attempting to add the user to the same room twice, causing all sorts of issues. Can someone please work out the ActionListeners?
