### ISSUE TITLE
New networking separator character

### ISSUE THREAD

**Issue by lekro** [rpbeltran/closed-kimono#6]
@legomaniack - I see why you said that the colon won't work for the separator. How about a comma, or a semicolon? I don't foresee any problems with that.

**Comment by legomaniack** [comment]
Think about it - storing in plaintext, that means that the user cannot send any messages that have the separator character in them - And I personally use commas and semicolons, I don't know about you. It needs to be something obscure so it has no issues being removed if typed.

**Comment by lekro** [comment]
I see... I wasn't thinking that through.

Let's use the **tab character**. The user can't type that anyway (and we should check to make sure)

**Comment by lekro** [comment]
I would like to note that we switched to ascii separator characters 30 and 31 in abb6665e3c85936e9dea0d2d446b520ddc2cab5a.
