### ISSUE TITLE
Client never actually gets the input

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#7]
The messages are echoed, but there isn't any method to receive the input stream. There's a method to handle input, but there's nothing connecting that to the Input/OutputStream. Not to mention the server is just not actually handling messages properly to begin with.

**Comment by lekro** [comment]
The client should now be receiving the messages from the server. The issue was that the thread to receive messages wasn't started at all.

Please verify if the latest commit eac3ef0dfe05de43a492e1e61c4e5f39f2e5a889 fixes this.

**Comment by lekro** [comment]
Fixed by eac3ef0dfe05de43a492e1e61c4e5f39f2e5a889.
