### ISSUE TITLE
Message Length

### ISSUE THREAD

**Issue by legomaniack** [rpbeltran/closed-kimono#9]
If the message length exceeds the size of the box, it just kinda breaks everything.

The current system is basically set up to handle that, but it needs two things.
* A function to tell how many characters can fit in the TextArea
* A function to break a string into `n` or less length substrings.

**Comment by lekro** [comment]
We should implement a line wrapping function (or just enable it because Java might already have one built in)

**Comment by legomaniack** [comment]
Yeah, I made the system so that the list of lines on the screen is separate from the actual incoming messages, but I haven't bothered to actually tell it to split it up yet.

**Comment by lekro** [comment]
Well done on the chat system btw.

**Comment by lekro** [comment]
Ok, chats are working for me. Do you want to test on your side as well?

**Comment by legomaniack** [comment]
We should probably swap the JTextArea to some kinda scroll pane. There are ways to handle line wrapping automagically, and the only thing stopping me from doing that was that it would break horizontal scrolling; a scrolling view would take care of that.
